/**
 * generated by Xtext 2.13.0
 */
package ac.soton.bsharp.bSharp;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ac.soton.bsharp.bSharp.BSharpPackage#getExpressionType()
 * @model
 * @generated
 */
public interface ExpressionType extends ExpressionVariable
{
} // ExpressionType
