/**
 * generated by Xtext 2.14.0
 */
package ac.soton.bsharp.bSharp.tests;

import ac.soton.bsharp.bSharp.BSharpFactory;
import ac.soton.bsharp.bSharp.FuncCallArgs;

import junit.framework.TestCase;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Func Call Args</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class FuncCallArgsTest extends TestCase {

	/**
	 * The fixture for this Func Call Args test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FuncCallArgs fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(FuncCallArgsTest.class);
	}

	/**
	 * Constructs a new Func Call Args test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public FuncCallArgsTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Func Call Args test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(FuncCallArgs fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Func Call Args test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FuncCallArgs getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(BSharpFactory.eINSTANCE.createFuncCallArgs());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //FuncCallArgsTest
