/*
 * generated by Xtext 2.13.0
 */
package ac.soton.bsharp.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractBSharpValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(ac.soton.bsharp.bSharp.BSharpPackage.eINSTANCE);
		return result;
	}
	
}
