/* Definition of the Pred type, this allows it to be used within the language
 * I'd rather build this using emf then I would be able to use unicode charaters
 * but I can't figure out how to add EMF to the resource set. Unlike other types
 * when compiling Pred is special cased to allow it to interact with the two Event-B
 * types, its predicates and its BOOL set.
 */

Datatype Pred
| true
| false
{
	not(a:Pred) : Pred match a {
		| true : false
		| false : true
	}
}
