/**
 * generated by Xtext 2.12.0
 */
package ac.soton.bsharp.validation;

import ac.soton.bsharp.bSharp.Infix;
import ac.soton.bsharp.validation.AbstractBSharpValidator;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.xbase.lib.InputOutput;
import rewriteAST.ASTRewriter;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class BSharpValidator extends AbstractBSharpValidator {
  public final static String UNEXPECTED_POLY_CONTEXT = "unexpectedPolyContext";
  
  public final static String POLYMORPHIC_TYPE_OUT_OF_SCOPE = "PolymorphicTypeOutOfScope";
  
  @Check
  public Infix checkExpressionTree(final Infix expression) {
    Infix _xblockexpression = null;
    {
      Infix copy = EcoreUtil2.<Infix>copy(expression);
      copy = ASTRewriter.reorderInfixTree(copy);
      Infix copy2 = EcoreUtil2.<Infix>copy(expression);
      InputOutput.<String>print("\n\n");
      InputOutput.<String>print(copy2.constructLatexExpressionTree(""));
      InputOutput.<String>print("\n\n\n");
      _xblockexpression = InputOutput.<Infix>print(copy);
    }
    return _xblockexpression;
  }
}
