/**
 * generated by Xtext 2.14.0
 */
package ac.soton.bsharp.bSharp;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see ac.soton.bsharp.bSharp.BSharpPackage
 * @generated
 */
public interface BSharpFactory extends EFactory {
	/**
	 * The singleton instance of the factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	BSharpFactory eINSTANCE = ac.soton.bsharp.bSharp.impl.BSharpFactoryImpl.init();

	/**
	 * Returns a new object of class '<em>Top Level</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Top Level</em>'.
	 * @generated
	 */
	TopLevel createTopLevel();

	/**
	 * Returns a new object of class '<em>Top Level File</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Top Level File</em>'.
	 * @generated
	 */
	TopLevelFile createTopLevelFile();

	/**
	 * Returns a new object of class '<em>Top Level Import</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Top Level Import</em>'.
	 * @generated
	 */
	TopLevelImport createTopLevelImport();

	/**
	 * Returns a new object of class '<em>Tuple</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Tuple</em>'.
	 * @generated
	 */
	Tuple createTuple();

	/**
	 * Returns a new object of class '<em>Block</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Block</em>'.
	 * @generated
	 */
	BSharpBlock createBSharpBlock();

	/**
	 * Returns a new object of class '<em>Poly Context</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Poly Context</em>'.
	 * @generated
	 */
	PolyContext createPolyContext();

	/**
	 * Returns a new object of class '<em>Poly Type</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Poly Type</em>'.
	 * @generated
	 */
	PolyType createPolyType();

	/**
	 * Returns a new object of class '<em>Super Type List</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Super Type List</em>'.
	 * @generated
	 */
	SuperTypeList createSuperTypeList();

	/**
	 * Returns a new object of class '<em>Constructed Type</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Constructed Type</em>'.
	 * @generated
	 */
	ConstructedType createConstructedType();

	/**
	 * Returns a new object of class '<em>Type Constructor</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Type Constructor</em>'.
	 * @generated
	 */
	TypeConstructor createTypeConstructor();

	/**
	 * Returns a new object of class '<em>Type Constr Bracket</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Type Constr Bracket</em>'.
	 * @generated
	 */
	TypeConstrBracket createTypeConstrBracket();

	/**
	 * Returns a new object of class '<em>Type Decl Context</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Type Decl Context</em>'.
	 * @generated
	 */
	TypeDeclContext createTypeDeclContext();

	/**
	 * Returns a new object of class '<em>Where</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Where</em>'.
	 * @generated
	 */
	Where createWhere();

	/**
	 * Returns a new object of class '<em>Wrapped Infix</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Wrapped Infix</em>'.
	 * @generated
	 */
	WrappedInfix createWrappedInfix();

	/**
	 * Returns a new object of class '<em>Datatype</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Datatype</em>'.
	 * @generated
	 */
	Datatype createDatatype();

	/**
	 * Returns a new object of class '<em>Datatype Constructor</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Datatype Constructor</em>'.
	 * @generated
	 */
	DatatypeConstructor createDatatypeConstructor();

	/**
	 * Returns a new object of class '<em>Extend</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Extend</em>'.
	 * @generated
	 */
	Extend createExtend();

	/**
	 * Returns a new object of class '<em>Function Decl</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Function Decl</em>'.
	 * @generated
	 */
	FunctionDecl createFunctionDecl();

	/**
	 * Returns a new object of class '<em>Match Statement</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Match Statement</em>'.
	 * @generated
	 */
	MatchStatement createMatchStatement();

	/**
	 * Returns a new object of class '<em>Match Case</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Match Case</em>'.
	 * @generated
	 */
	MatchCase createMatchCase();

	/**
	 * Returns a new object of class '<em>Theorem Body</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Theorem Body</em>'.
	 * @generated
	 */
	TheoremBody createTheoremBody();

	/**
	 * Returns a new object of class '<em>Theorem Decl</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Theorem Decl</em>'.
	 * @generated
	 */
	TheoremDecl createTheoremDecl();

	/**
	 * Returns a new object of class '<em>Typed Variable List</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Typed Variable List</em>'.
	 * @generated
	 */
	TypedVariableList createTypedVariableList();

	/**
	 * Returns a new object of class '<em>Variable Typing</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Variable Typing</em>'.
	 * @generated
	 */
	VariableTyping createVariableTyping();

	/**
	 * Returns a new object of class '<em>Typed Variable</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Typed Variable</em>'.
	 * @generated
	 */
	TypedVariable createTypedVariable();

	/**
	 * Returns a new object of class '<em>Quant Lambda</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Quant Lambda</em>'.
	 * @generated
	 */
	QuantLambda createQuantLambda();

	/**
	 * Returns a new object of class '<em>Referencing Func</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Referencing Func</em>'.
	 * @generated
	 */
	ReferencingFunc createReferencingFunc();

	/**
	 * Returns a new object of class '<em>Expression</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Expression</em>'.
	 * @generated
	 */
	Expression createExpression();

	/**
	 * Returns a new object of class '<em>Function Call</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Function Call</em>'.
	 * @generated
	 */
	FunctionCall createFunctionCall();

	/**
	 * Returns a new object of class '<em>Function Call Inbuilt</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Function Call Inbuilt</em>'.
	 * @generated
	 */
	FunctionCallInbuilt createFunctionCallInbuilt();

	/**
	 * Returns a new object of class '<em>Func Call Args</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Func Call Args</em>'.
	 * @generated
	 */
	FuncCallArgs createFuncCallArgs();

	/**
	 * Returns a new object of class '<em>Class Var Decl</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Class Var Decl</em>'.
	 * @generated
	 */
	ClassVarDecl createClassVarDecl();

	/**
	 * Returns a new object of class '<em>Prefix</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Prefix</em>'.
	 * @generated
	 */
	Prefix createPrefix();

	/**
	 * Returns a new object of class '<em>Bracket</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Bracket</em>'.
	 * @generated
	 */
	Bracket createBracket();

	/**
	 * Returns a new object of class '<em>Instance</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Instance</em>'.
	 * @generated
	 */
	Instance createInstance();

	/**
	 * Returns a new object of class '<em>Infix</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Infix</em>'.
	 * @generated
	 */
	Infix createInfix();

	/**
	 * Returns a new object of class '<em>Named Object</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Named Object</em>'.
	 * @generated
	 */
	NamedObject createNamedObject();

	/**
	 * Returns a new object of class '<em>Type Power Set</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Type Power Set</em>'.
	 * @generated
	 */
	TypePowerSet createTypePowerSet();

	/**
	 * Returns a new object of class '<em>Global Import</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Global Import</em>'.
	 * @generated
	 */
	GlobalImport createGlobalImport();

	/**
	 * Returns a new object of class '<em>If Else</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>If Else</em>'.
	 * @generated
	 */
	IfElse createIfElse();

	/**
	 * Returns a new object of class '<em>Inbuilt Infix</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Inbuilt Infix</em>'.
	 * @generated
	 */
	InbuiltInfix createInbuiltInfix();

	/**
	 * Returns a new object of class '<em>Inbuilt Prefix Func Name</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Inbuilt Prefix Func Name</em>'.
	 * @generated
	 */
	InbuiltPrefixFuncName createInbuiltPrefixFuncName();

	/**
	 * Returns a new object of class '<em>File Import</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>File Import</em>'.
	 * @generated
	 */
	FileImport createFileImport();

	/**
	 * Returns a new object of class '<em>Local Import</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Local Import</em>'.
	 * @generated
	 */
	LocalImport createLocalImport();

	/**
	 * Returns a new object of class '<em>BS Class</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>BS Class</em>'.
	 * @generated
	 */
	BSClass createBSClass();

	/**
	 * Returns a new object of class '<em>Inst Name</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Inst Name</em>'.
	 * @generated
	 */
	InstName createInstName();

	/**
	 * Returns the package supported by this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the package supported by this factory.
	 * @generated
	 */
	BSharpPackage getBSharpPackage();

} //BSharpFactory
