/**
 * generated by Xtext 2.14.0
 */
package ac.soton.bsharp.bSharp;

import java.util.List;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Class Var Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ac.soton.bsharp.bSharp.ClassVarDecl#getOwnerType <em>Owner Type</em>}</li>
 *   <li>{@link ac.soton.bsharp.bSharp.ClassVarDecl#getTypeVar <em>Type Var</em>}</li>
 *   <li>{@link ac.soton.bsharp.bSharp.ClassVarDecl#getTypedVar <em>Typed Var</em>}</li>
 * </ul>
 *
 * @see ac.soton.bsharp.bSharp.BSharpPackage#getClassVarDecl()
 * @model
 * @generated
 */
public interface ClassVarDecl extends IVarType {
	/**
	 * Returns the value of the '<em><b>Owner Type</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Owner Type</em>' reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Owner Type</em>' reference.
	 * @see #setOwnerType(GenName)
	 * @see ac.soton.bsharp.bSharp.BSharpPackage#getClassVarDecl_OwnerType()
	 * @model
	 * @generated
	 */
	GenName getOwnerType();

	/**
	 * Sets the value of the '{@link ac.soton.bsharp.bSharp.ClassVarDecl#getOwnerType <em>Owner Type</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Owner Type</em>' reference.
	 * @see #getOwnerType()
	 * @generated
	 */
	void setOwnerType(GenName value);

	/**
	 * Returns the value of the '<em><b>Type Var</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Type Var</em>' reference.
	 * @see #setTypeVar(ExpressionVariable)
	 * @see ac.soton.bsharp.bSharp.BSharpPackage#getClassVarDecl_TypeVar()
	 * @model
	 * @generated
	 */
	ExpressionVariable getTypeVar();

	/**
	 * Sets the value of the '{@link ac.soton.bsharp.bSharp.ClassVarDecl#getTypeVar <em>Type Var</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Type Var</em>' reference.
	 * @see #getTypeVar()
	 * @generated
	 */
	void setTypeVar(ExpressionVariable value);

	/**
	 * Returns the value of the '<em><b>Typed Var</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Typed Var</em>' reference.
	 * @see #setTypedVar(TypedVariable)
	 * @see ac.soton.bsharp.bSharp.BSharpPackage#getClassVarDecl_TypedVar()
	 * @model
	 * @generated
	 */
	TypedVariable getTypedVar();

	/**
	 * Sets the value of the '{@link ac.soton.bsharp.bSharp.ClassVarDecl#getTypedVar <em>Typed Var</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Typed Var</em>' reference.
	 * @see #getTypedVar()
	 * @generated
	 */
	void setTypedVar(TypedVariable value);

	boolean referencesContainingType();

	TypeBuilder calculateReturnType(TypeDeclContext ctx, List<Expression> args);

	TypeBuilder calculateType();

} // ClassVarDecl
