/**
 * generated by Xtext 2.14.0
 */
package ac.soton.bsharp.bSharp;

import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.emf.ecore.EObject;
import org.eventb.theory.core.IDatatypeDefinition;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Datatype Constructor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ac.soton.bsharp.bSharp.DatatypeConstructor#getName <em>Name</em>}</li>
 *   <li>{@link ac.soton.bsharp.bSharp.DatatypeConstructor#getDecons <em>Decons</em>}</li>
 * </ul>
 *
 * @see ac.soton.bsharp.bSharp.BSharpPackage#getDatatypeConstructor()
 * @model
 */
public interface DatatypeConstructor extends IVariableProvider, TypedVariable {
	/**
	 * Returns the value of the '<em><b>Decons</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Decons</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Decons</em>' containment reference.
	 * @see #setDecons(TypedVariableList)
	 * @see ac.soton.bsharp.bSharp.BSharpPackage#getDatatypeConstructor_Decons()
	 * @model containment="true"
	 * @generated
	 */
	TypedVariableList getDecons();

	/**
	 * Sets the value of the '{@link ac.soton.bsharp.bSharp.DatatypeConstructor#getDecons <em>Decons</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Decons</em>' containment reference.
	 * @see #getDecons()
	 * @generated
	 */
	void setDecons(TypedVariableList value);

	void compileInto(IDatatypeDefinition datatype, IProgressMonitor monitor);

} // DatatypeConstructor
