/**
 * generated by Xtext 2.14.0
 */
package ac.soton.bsharp.bSharp;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Inst Name</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ac.soton.bsharp.bSharp.BSharpPackage#getInstName()
 * @model
 * @generated
 */
public interface InstName extends ExpressionVariable, GenName {
} // InstName
