/**
 * generated by Xtext 2.14.0
 */
package ac.soton.bsharp.bSharp;

import org.eclipse.emf.ecore.EObject;

import ac.soton.bsharp.theory.util.TheoryImportCache;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ITheory Import Cache Provider</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ac.soton.bsharp.bSharp.BSharpPackage#getITheoryImportCacheProvider()
 * @model abstract="true"
 * @generated
 */
public interface ITheoryImportCacheProvider extends EObject {
	
	/* When compiling an EventB file it is useful to have a location to cache some
	 * of the inoformation about the file, this protocol is adopted by the areas of
	 * EMF tree that cause a new file to be created, when a new file is created, a 
	 * cache is created and the appropiate class has the cache set, which can then 
	 * be got later.
	 */
	TheoryImportCache getTheoryImportCache();
	void setTheoryImportCache(TheoryImportCache thyCache);
	
} // ITheoryImportCacheProvider
