/**
 * generated by Xtext 2.14.0
 */
package ac.soton.bsharp.bSharp;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Referencing Func</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ac.soton.bsharp.bSharp.ReferencingFunc#getReferencedFunc <em>Referenced Func</em>}</li>
 * </ul>
 *
 * @see ac.soton.bsharp.bSharp.BSharpPackage#getReferencingFunc()
 * @model
 * @generated
 */
public interface ReferencingFunc extends FunctionDecl {
	/**
	 * Returns the value of the '<em><b>Referenced Func</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Referenced Func</em>' reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Referenced Func</em>' reference.
	 * @see #setReferencedFunc(FunctionDecl)
	 * @see ac.soton.bsharp.bSharp.BSharpPackage#getReferencingFunc_ReferencedFunc()
	 * @model
	 * @generated
	 */
	FunctionDecl getReferencedFunc();

	/**
	 * Sets the value of the '{@link ac.soton.bsharp.bSharp.ReferencingFunc#getReferencedFunc <em>Referenced Func</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Referenced Func</em>' reference.
	 * @see #getReferencedFunc()
	 * @generated
	 */
	void setReferencedFunc(FunctionDecl value);

} // ReferencingFunc
