<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bSharp" nsURI="http://www.soton.ac/bsharp/BSharp" nsPrefix="bSharp">
  <eClassifiers xsi:type="ecore:EClass" name="DomainModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//TopLevel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopLevel"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImportStatement" eSuperTypes="#//TopLevel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importName" upperBound="-1"
        eType="#//ImportComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDecl" eSuperTypes="#//TopLevel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeName" eType="#//TypeName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//PolyContext"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyElements" upperBound="-1"
        eType="#//TypeBodyElements" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BppClass" eSuperTypes="#//ClassDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="supertypes" eType="#//SuperTypeList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="varList" eType="#//TypeStructure"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="where" eType="#//Where"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeName" eSuperTypes="#//GenName #//ExpressionType"/>
  <eClassifiers xsi:type="ecore:EClass" name="PolymorphicTypeName" eSuperTypes="#//GenName"/>
  <eClassifiers xsi:type="ecore:EClass" name="PolyContext">
    <eStructuralFeatures xsi:type="ecore:EReference" name="polyTypes" upperBound="-1"
        eType="#//PolyContextTypes" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PolyContextTypes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//PolymorphicTypeName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//PolyTypeConstraints" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PolyTypeConstraints">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TypeName" unique="false"
        upperBound="-1" eType="#//TypeName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperTypeList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" upperBound="-1"
        eType="#//ConstructedType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstructedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeConstructor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TypeName" eType="#//GenName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" upperBound="-1"
        eType="#//TypeDeclContext" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDeclContext">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TypeName" upperBound="-1"
        eType="#//ConstructedType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" eType="#//TypedVariableList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Where">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expessions" upperBound="-1"
        eType="#//QuantLambda" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Datatype" eSuperTypes="#//ClassDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="varList" upperBound="-1"
        eType="#//DatatypeConstructor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatatypeConstructor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//TypedVariable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decons" eType="#//TypedVariableList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Extend" eSuperTypes="#//TopLevel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//TypeName"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyElements" upperBound="-1"
        eType="#//TypeBodyElements" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeBodyElements">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" upperBound="-1"
        eType="#//FunctionDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theorems" upperBound="-1"
        eType="#//TheoremBody" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//PolyContext"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="varList" eType="#//TypedVariableList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//TypeConstructor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="infix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precedence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//FunctionName"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionName" eSuperTypes="#//ExpressionVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatchStatement" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="match" eType="#//TypedVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inductCase" upperBound="-1"
        eType="#//MatchCase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatchCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deconName" eType="#//TypedVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//TypedVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TheoremBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="theoremDecl" upperBound="-1"
        eType="#//TheoremDecl" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TheoremDecl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="thmName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedVariableList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variablesOfType" upperBound="-1"
        eType="#//VariableTyping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableTyping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeVar" upperBound="-1"
        eType="#//TypedVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ConstructedType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedVariable" eSuperTypes="#//ExpressionVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TypeName" eType="#//TypeName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//TypeDeclContext"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuantLambda" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//PolyContext"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="varList" eType="#//TypedVariableList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeInst" eType="#//TypeInstance"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Prefix" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elem" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bracket" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionType" eSuperTypes="#//ExpressionVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" eType="#//ExpressionVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeName" eType="#//GenName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" unique="false"
        upperBound="-1" eType="#//TypedVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InbuiltTypeScan" eSuperTypes="#//TypeConstructor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instance" eSuperTypes="#//TopLevel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="className" eType="#//TypeName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//TypeDeclContext"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Infix" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="funcName" eType="#//FunctionName"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
