/**
 * generated by Xtext 2.13.0
 */
package org.xtext.sampleProj.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Extend</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sampleProj.mydsl.myDsl.Extend#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.sampleProj.mydsl.myDsl.Extend#getExtesnion <em>Extesnion</em>}</li>
 * </ul>
 *
 * @see org.xtext.sampleProj.mydsl.myDsl.MyDslPackage#getExtend()
 * @model
 * @generated
 */
public interface Extend extends ClassDecl
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(TypeName)
   * @see org.xtext.sampleProj.mydsl.myDsl.MyDslPackage#getExtend_Name()
   * @model
   * @generated
   */
  TypeName getName();

  /**
   * Sets the value of the '{@link org.xtext.sampleProj.mydsl.myDsl.Extend#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(TypeName value);

  /**
   * Returns the value of the '<em><b>Extesnion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Extesnion</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extesnion</em>' attribute.
   * @see #setExtesnion(String)
   * @see org.xtext.sampleProj.mydsl.myDsl.MyDslPackage#getExtend_Extesnion()
   * @model
   * @generated
   */
  String getExtesnion();

  /**
   * Sets the value of the '{@link org.xtext.sampleProj.mydsl.myDsl.Extend#getExtesnion <em>Extesnion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Extesnion</em>' attribute.
   * @see #getExtesnion()
   * @generated
   */
  void setExtesnion(String value);

} // Extend
