/**
 * generated by Xtext 2.13.0
 */
package org.xtext.sampleProj.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sampleProj.mydsl.myDsl.Instance#getClassName <em>Class Name</em>}</li>
 *   <li>{@link org.xtext.sampleProj.mydsl.myDsl.Instance#getContext <em>Context</em>}</li>
 *   <li>{@link org.xtext.sampleProj.mydsl.myDsl.Instance#getArguments <em>Arguments</em>}</li>
 * </ul>
 *
 * @see org.xtext.sampleProj.mydsl.myDsl.MyDslPackage#getInstance()
 * @model
 * @generated
 */
public interface Instance extends TopLevel
{
  /**
   * Returns the value of the '<em><b>Class Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Class Name</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class Name</em>' reference.
   * @see #setClassName(TypeName)
   * @see org.xtext.sampleProj.mydsl.myDsl.MyDslPackage#getInstance_ClassName()
   * @model
   * @generated
   */
  TypeName getClassName();

  /**
   * Sets the value of the '{@link org.xtext.sampleProj.mydsl.myDsl.Instance#getClassName <em>Class Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class Name</em>' reference.
   * @see #getClassName()
   * @generated
   */
  void setClassName(TypeName value);

  /**
   * Returns the value of the '<em><b>Context</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Context</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context</em>' containment reference.
   * @see #setContext(TypeDeclContext)
   * @see org.xtext.sampleProj.mydsl.myDsl.MyDslPackage#getInstance_Context()
   * @model containment="true"
   * @generated
   */
  TypeDeclContext getContext();

  /**
   * Sets the value of the '{@link org.xtext.sampleProj.mydsl.myDsl.Instance#getContext <em>Context</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context</em>' containment reference.
   * @see #getContext()
   * @generated
   */
  void setContext(TypeDeclContext value);

  /**
   * Returns the value of the '<em><b>Arguments</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sampleProj.mydsl.myDsl.Expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arguments</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arguments</em>' containment reference list.
   * @see org.xtext.sampleProj.mydsl.myDsl.MyDslPackage#getInstance_Arguments()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getArguments();

} // Instance
