/**
 * generated by Xtext 2.12.0
 */
package org.xtext.sampleProj.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.sampleProj.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/sampleProj/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.DomainModelImpl <em>Domain Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.DomainModelImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getDomainModel()
   * @generated
   */
  int DOMAIN_MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Domain Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.TopLevelImpl <em>Top Level</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.TopLevelImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getTopLevel()
   * @generated
   */
  int TOP_LEVEL = 1;

  /**
   * The number of structural features of the '<em>Top Level</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.ImportSatementImpl <em>Import Satement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.ImportSatementImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getImportSatement()
   * @generated
   */
  int IMPORT_SATEMENT = 2;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_SATEMENT__IMPORTS = TOP_LEVEL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Import Satement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_SATEMENT_FEATURE_COUNT = TOP_LEVEL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.ImportImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 3;

  /**
   * The feature id for the '<em><b>Import Name</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__IMPORT_NAME = 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.ImportComponentImpl <em>Import Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.ImportComponentImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getImportComponent()
   * @generated
   */
  int IMPORT_COMPONENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_COMPONENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Import Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_COMPONENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.ClassDeclImpl <em>Class Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.ClassDeclImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getClassDecl()
   * @generated
   */
  int CLASS_DECL = 5;

  /**
   * The feature id for the '<em><b>Body Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DECL__BODY_ELEMENTS = TOP_LEVEL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Class Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DECL_FEATURE_COUNT = TOP_LEVEL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.PolyContextImpl <em>Poly Context</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.PolyContextImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getPolyContext()
   * @generated
   */
  int POLY_CONTEXT = 6;

  /**
   * The feature id for the '<em><b>Poly Types</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLY_CONTEXT__POLY_TYPES = 0;

  /**
   * The number of structural features of the '<em>Poly Context</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLY_CONTEXT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.PolyContextTypesImpl <em>Poly Context Types</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.PolyContextTypesImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getPolyContextTypes()
   * @generated
   */
  int POLY_CONTEXT_TYPES = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLY_CONTEXT_TYPES__NAME = 0;

  /**
   * The feature id for the '<em><b>Constraints</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLY_CONTEXT_TYPES__CONSTRAINTS = 1;

  /**
   * The number of structural features of the '<em>Poly Context Types</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLY_CONTEXT_TYPES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.TypeConstraintsImpl <em>Type Constraints</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.TypeConstraintsImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getTypeConstraints()
   * @generated
   */
  int TYPE_CONSTRAINTS = 8;

  /**
   * The feature id for the '<em><b>Type Name</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_CONSTRAINTS__TYPE_NAME = 0;

  /**
   * The number of structural features of the '<em>Type Constraints</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_CONSTRAINTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.TypedVariableImpl <em>Typed Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.TypedVariableImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getTypedVariable()
   * @generated
   */
  int TYPED_VARIABLE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPED_VARIABLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Constraints</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPED_VARIABLE__CONSTRAINTS = 1;

  /**
   * The number of structural features of the '<em>Typed Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPED_VARIABLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.TypeDeclarationImpl <em>Type Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.TypeDeclarationImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getTypeDeclaration()
   * @generated
   */
  int TYPE_DECLARATION = 10;

  /**
   * The feature id for the '<em><b>Type Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_DECLARATION__TYPE_NAME = 0;

  /**
   * The feature id for the '<em><b>Context</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_DECLARATION__CONTEXT = 1;

  /**
   * The number of structural features of the '<em>Type Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_DECLARATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.TypeDeclContextImpl <em>Type Decl Context</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.TypeDeclContextImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getTypeDeclContext()
   * @generated
   */
  int TYPE_DECL_CONTEXT = 11;

  /**
   * The feature id for the '<em><b>Type Name</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_DECL_CONTEXT__TYPE_NAME = 0;

  /**
   * The number of structural features of the '<em>Type Decl Context</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_DECL_CONTEXT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.TypeNameImpl <em>Type Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.TypeNameImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getTypeName()
   * @generated
   */
  int TYPE_NAME = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_NAME__NAME = 0;

  /**
   * The number of structural features of the '<em>Type Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.FunctionNameImpl <em>Function Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.FunctionNameImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getFunctionName()
   * @generated
   */
  int FUNCTION_NAME = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_NAME__NAME = 0;

  /**
   * The number of structural features of the '<em>Function Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.SupertypeImpl <em>Supertype</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.SupertypeImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getSupertype()
   * @generated
   */
  int SUPERTYPE = 14;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUPERTYPE__SUPER_TYPE = 0;

  /**
   * The number of structural features of the '<em>Supertype</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUPERTYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.WhereImpl <em>Where</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.WhereImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getWhere()
   * @generated
   */
  int WHERE = 15;

  /**
   * The feature id for the '<em><b>Expessions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE__EXPESSIONS = 0;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE__EXPRESSIONS = 1;

  /**
   * The number of structural features of the '<em>Where</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.ClassImpl <em>Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.ClassImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getClass_()
   * @generated
   */
  int CLASS = 16;

  /**
   * The feature id for the '<em><b>Body Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__BODY_ELEMENTS = CLASS_DECL__BODY_ELEMENTS;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__NAME = CLASS_DECL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Context</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__CONTEXT = CLASS_DECL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_FEATURE_COUNT = CLASS_DECL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.DatatypeImpl <em>Datatype</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.DatatypeImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getDatatype()
   * @generated
   */
  int DATATYPE = 17;

  /**
   * The feature id for the '<em><b>Body Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPE__BODY_ELEMENTS = CLASS_DECL__BODY_ELEMENTS;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPE__NAME = CLASS_DECL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Context</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPE__CONTEXT = CLASS_DECL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Constructors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPE__CONSTRUCTORS = CLASS_DECL_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Datatype</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPE_FEATURE_COUNT = CLASS_DECL_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.DatatypeConstructorImpl <em>Datatype Constructor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.DatatypeConstructorImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getDatatypeConstructor()
   * @generated
   */
  int DATATYPE_CONSTRUCTOR = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPE_CONSTRUCTOR__NAME = 0;

  /**
   * The number of structural features of the '<em>Datatype Constructor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPE_CONSTRUCTOR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.BaseConstructorImpl <em>Base Constructor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.BaseConstructorImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getBaseConstructor()
   * @generated
   */
  int BASE_CONSTRUCTOR = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASE_CONSTRUCTOR__NAME = DATATYPE_CONSTRUCTOR__NAME;

  /**
   * The number of structural features of the '<em>Base Constructor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASE_CONSTRUCTOR_FEATURE_COUNT = DATATYPE_CONSTRUCTOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.ConstructorImpl <em>Constructor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.ConstructorImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getConstructor()
   * @generated
   */
  int CONSTRUCTOR = 20;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRUCTOR__NAME = DATATYPE_CONSTRUCTOR__NAME;

  /**
   * The feature id for the '<em><b>Typed Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRUCTOR__TYPED_VARIABLES = DATATYPE_CONSTRUCTOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Constructor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRUCTOR_FEATURE_COUNT = DATATYPE_CONSTRUCTOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.ExtendImpl <em>Extend</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.ExtendImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getExtend()
   * @generated
   */
  int EXTEND = 21;

  /**
   * The feature id for the '<em><b>Body Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTEND__BODY_ELEMENTS = CLASS_DECL__BODY_ELEMENTS;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTEND__NAME = CLASS_DECL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Extesnion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTEND__EXTESNION = CLASS_DECL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Extend</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTEND_FEATURE_COUNT = CLASS_DECL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.TypeBodyElementsImpl <em>Type Body Elements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.TypeBodyElementsImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getTypeBodyElements()
   * @generated
   */
  int TYPE_BODY_ELEMENTS = 22;

  /**
   * The feature id for the '<em><b>Functions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_BODY_ELEMENTS__FUNCTIONS = 0;

  /**
   * The feature id for the '<em><b>Theorems</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_BODY_ELEMENTS__THEOREMS = 1;

  /**
   * The number of structural features of the '<em>Type Body Elements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_BODY_ELEMENTS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.FunctionDeclImpl <em>Function Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.FunctionDeclImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getFunctionDecl()
   * @generated
   */
  int FUNCTION_DECL = 23;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DECL__NAME = 0;

  /**
   * The feature id for the '<em><b>Type Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DECL__TYPE_VARIABLES = 1;

  /**
   * The number of structural features of the '<em>Function Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DECL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.ExpressionImpl
   * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 24;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__NAME = 0;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.DomainModel <em>Domain Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domain Model</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.DomainModel
   * @generated
   */
  EClass getDomainModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sampleProj.mydsl.myDsl.DomainModel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.DomainModel#getElements()
   * @see #getDomainModel()
   * @generated
   */
  EReference getDomainModel_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.TopLevel <em>Top Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Top Level</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.TopLevel
   * @generated
   */
  EClass getTopLevel();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.ImportSatement <em>Import Satement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import Satement</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.ImportSatement
   * @generated
   */
  EClass getImportSatement();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sampleProj.mydsl.myDsl.ImportSatement#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.ImportSatement#getImports()
   * @see #getImportSatement()
   * @generated
   */
  EReference getImportSatement_Imports();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sampleProj.mydsl.myDsl.Import#getImportName <em>Import Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Import Name</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Import#getImportName()
   * @see #getImport()
   * @generated
   */
  EReference getImport_ImportName();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.ImportComponent <em>Import Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import Component</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.ImportComponent
   * @generated
   */
  EClass getImportComponent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sampleProj.mydsl.myDsl.ImportComponent#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.ImportComponent#getName()
   * @see #getImportComponent()
   * @generated
   */
  EAttribute getImportComponent_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.ClassDecl <em>Class Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class Decl</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.ClassDecl
   * @generated
   */
  EClass getClassDecl();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sampleProj.mydsl.myDsl.ClassDecl#getBodyElements <em>Body Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Body Elements</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.ClassDecl#getBodyElements()
   * @see #getClassDecl()
   * @generated
   */
  EReference getClassDecl_BodyElements();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.PolyContext <em>Poly Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Poly Context</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.PolyContext
   * @generated
   */
  EClass getPolyContext();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sampleProj.mydsl.myDsl.PolyContext#getPolyTypes <em>Poly Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Poly Types</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.PolyContext#getPolyTypes()
   * @see #getPolyContext()
   * @generated
   */
  EReference getPolyContext_PolyTypes();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.PolyContextTypes <em>Poly Context Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Poly Context Types</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.PolyContextTypes
   * @generated
   */
  EClass getPolyContextTypes();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sampleProj.mydsl.myDsl.PolyContextTypes#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.PolyContextTypes#getName()
   * @see #getPolyContextTypes()
   * @generated
   */
  EAttribute getPolyContextTypes_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sampleProj.mydsl.myDsl.PolyContextTypes#getConstraints <em>Constraints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Constraints</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.PolyContextTypes#getConstraints()
   * @see #getPolyContextTypes()
   * @generated
   */
  EReference getPolyContextTypes_Constraints();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.TypeConstraints <em>Type Constraints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Constraints</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.TypeConstraints
   * @generated
   */
  EClass getTypeConstraints();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.sampleProj.mydsl.myDsl.TypeConstraints#getTypeName <em>Type Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Type Name</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.TypeConstraints#getTypeName()
   * @see #getTypeConstraints()
   * @generated
   */
  EReference getTypeConstraints_TypeName();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.TypedVariable <em>Typed Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Typed Variable</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.TypedVariable
   * @generated
   */
  EClass getTypedVariable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sampleProj.mydsl.myDsl.TypedVariable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.TypedVariable#getName()
   * @see #getTypedVariable()
   * @generated
   */
  EAttribute getTypedVariable_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sampleProj.mydsl.myDsl.TypedVariable#getConstraints <em>Constraints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Constraints</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.TypedVariable#getConstraints()
   * @see #getTypedVariable()
   * @generated
   */
  EReference getTypedVariable_Constraints();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.TypeDeclaration <em>Type Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Declaration</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.TypeDeclaration
   * @generated
   */
  EClass getTypeDeclaration();

  /**
   * Returns the meta object for the reference '{@link org.xtext.sampleProj.mydsl.myDsl.TypeDeclaration#getTypeName <em>Type Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type Name</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.TypeDeclaration#getTypeName()
   * @see #getTypeDeclaration()
   * @generated
   */
  EReference getTypeDeclaration_TypeName();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.sampleProj.mydsl.myDsl.TypeDeclaration#getContext <em>Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Context</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.TypeDeclaration#getContext()
   * @see #getTypeDeclaration()
   * @generated
   */
  EReference getTypeDeclaration_Context();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.TypeDeclContext <em>Type Decl Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Decl Context</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.TypeDeclContext
   * @generated
   */
  EClass getTypeDeclContext();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.sampleProj.mydsl.myDsl.TypeDeclContext#getTypeName <em>Type Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Type Name</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.TypeDeclContext#getTypeName()
   * @see #getTypeDeclContext()
   * @generated
   */
  EReference getTypeDeclContext_TypeName();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.TypeName <em>Type Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Name</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.TypeName
   * @generated
   */
  EClass getTypeName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sampleProj.mydsl.myDsl.TypeName#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.TypeName#getName()
   * @see #getTypeName()
   * @generated
   */
  EAttribute getTypeName_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.FunctionName <em>Function Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Name</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.FunctionName
   * @generated
   */
  EClass getFunctionName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sampleProj.mydsl.myDsl.FunctionName#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.FunctionName#getName()
   * @see #getFunctionName()
   * @generated
   */
  EAttribute getFunctionName_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.Supertype <em>Supertype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Supertype</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Supertype
   * @generated
   */
  EClass getSupertype();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sampleProj.mydsl.myDsl.Supertype#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Super Type</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Supertype#getSuperType()
   * @see #getSupertype()
   * @generated
   */
  EReference getSupertype_SuperType();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.Where <em>Where</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Where</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Where
   * @generated
   */
  EClass getWhere();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sampleProj.mydsl.myDsl.Where#getExpessions <em>Expessions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expessions</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Where#getExpessions()
   * @see #getWhere()
   * @generated
   */
  EReference getWhere_Expessions();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sampleProj.mydsl.myDsl.Where#getExpressions <em>Expressions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expressions</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Where#getExpressions()
   * @see #getWhere()
   * @generated
   */
  EReference getWhere_Expressions();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.Class <em>Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Class
   * @generated
   */
  EClass getClass_();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.sampleProj.mydsl.myDsl.Class#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Class#getName()
   * @see #getClass_()
   * @generated
   */
  EReference getClass_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sampleProj.mydsl.myDsl.Class#getContext <em>Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Context</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Class#getContext()
   * @see #getClass_()
   * @generated
   */
  EReference getClass_Context();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.Datatype <em>Datatype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Datatype</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Datatype
   * @generated
   */
  EClass getDatatype();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.sampleProj.mydsl.myDsl.Datatype#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Datatype#getName()
   * @see #getDatatype()
   * @generated
   */
  EReference getDatatype_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sampleProj.mydsl.myDsl.Datatype#getContext <em>Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Context</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Datatype#getContext()
   * @see #getDatatype()
   * @generated
   */
  EReference getDatatype_Context();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sampleProj.mydsl.myDsl.Datatype#getConstructors <em>Constructors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Constructors</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Datatype#getConstructors()
   * @see #getDatatype()
   * @generated
   */
  EReference getDatatype_Constructors();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.DatatypeConstructor <em>Datatype Constructor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Datatype Constructor</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.DatatypeConstructor
   * @generated
   */
  EClass getDatatypeConstructor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sampleProj.mydsl.myDsl.DatatypeConstructor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.DatatypeConstructor#getName()
   * @see #getDatatypeConstructor()
   * @generated
   */
  EAttribute getDatatypeConstructor_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.BaseConstructor <em>Base Constructor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Base Constructor</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.BaseConstructor
   * @generated
   */
  EClass getBaseConstructor();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.Constructor <em>Constructor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constructor</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Constructor
   * @generated
   */
  EClass getConstructor();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sampleProj.mydsl.myDsl.Constructor#getTypedVariables <em>Typed Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Typed Variables</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Constructor#getTypedVariables()
   * @see #getConstructor()
   * @generated
   */
  EReference getConstructor_TypedVariables();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.Extend <em>Extend</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Extend</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Extend
   * @generated
   */
  EClass getExtend();

  /**
   * Returns the meta object for the reference '{@link org.xtext.sampleProj.mydsl.myDsl.Extend#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Extend#getName()
   * @see #getExtend()
   * @generated
   */
  EReference getExtend_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sampleProj.mydsl.myDsl.Extend#getExtesnion <em>Extesnion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Extesnion</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Extend#getExtesnion()
   * @see #getExtend()
   * @generated
   */
  EAttribute getExtend_Extesnion();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.TypeBodyElements <em>Type Body Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Body Elements</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.TypeBodyElements
   * @generated
   */
  EClass getTypeBodyElements();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sampleProj.mydsl.myDsl.TypeBodyElements#getFunctions <em>Functions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Functions</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.TypeBodyElements#getFunctions()
   * @see #getTypeBodyElements()
   * @generated
   */
  EReference getTypeBodyElements_Functions();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.sampleProj.mydsl.myDsl.TypeBodyElements#getTheorems <em>Theorems</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Theorems</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.TypeBodyElements#getTheorems()
   * @see #getTypeBodyElements()
   * @generated
   */
  EAttribute getTypeBodyElements_Theorems();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.FunctionDecl <em>Function Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Decl</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.FunctionDecl
   * @generated
   */
  EClass getFunctionDecl();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sampleProj.mydsl.myDsl.FunctionDecl#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Name</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.FunctionDecl#getName()
   * @see #getFunctionDecl()
   * @generated
   */
  EReference getFunctionDecl_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sampleProj.mydsl.myDsl.FunctionDecl#getTypeVariables <em>Type Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Type Variables</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.FunctionDecl#getTypeVariables()
   * @see #getFunctionDecl()
   * @generated
   */
  EReference getFunctionDecl_TypeVariables();

  /**
   * Returns the meta object for class '{@link org.xtext.sampleProj.mydsl.myDsl.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sampleProj.mydsl.myDsl.Expression#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sampleProj.mydsl.myDsl.Expression#getName()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.DomainModelImpl <em>Domain Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.DomainModelImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getDomainModel()
     * @generated
     */
    EClass DOMAIN_MODEL = eINSTANCE.getDomainModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAIN_MODEL__ELEMENTS = eINSTANCE.getDomainModel_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.TopLevelImpl <em>Top Level</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.TopLevelImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getTopLevel()
     * @generated
     */
    EClass TOP_LEVEL = eINSTANCE.getTopLevel();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.ImportSatementImpl <em>Import Satement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.ImportSatementImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getImportSatement()
     * @generated
     */
    EClass IMPORT_SATEMENT = eINSTANCE.getImportSatement();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPORT_SATEMENT__IMPORTS = eINSTANCE.getImportSatement_Imports();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.ImportImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Import Name</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPORT__IMPORT_NAME = eINSTANCE.getImport_ImportName();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.ImportComponentImpl <em>Import Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.ImportComponentImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getImportComponent()
     * @generated
     */
    EClass IMPORT_COMPONENT = eINSTANCE.getImportComponent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT_COMPONENT__NAME = eINSTANCE.getImportComponent_Name();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.ClassDeclImpl <em>Class Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.ClassDeclImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getClassDecl()
     * @generated
     */
    EClass CLASS_DECL = eINSTANCE.getClassDecl();

    /**
     * The meta object literal for the '<em><b>Body Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_DECL__BODY_ELEMENTS = eINSTANCE.getClassDecl_BodyElements();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.PolyContextImpl <em>Poly Context</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.PolyContextImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getPolyContext()
     * @generated
     */
    EClass POLY_CONTEXT = eINSTANCE.getPolyContext();

    /**
     * The meta object literal for the '<em><b>Poly Types</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference POLY_CONTEXT__POLY_TYPES = eINSTANCE.getPolyContext_PolyTypes();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.PolyContextTypesImpl <em>Poly Context Types</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.PolyContextTypesImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getPolyContextTypes()
     * @generated
     */
    EClass POLY_CONTEXT_TYPES = eINSTANCE.getPolyContextTypes();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POLY_CONTEXT_TYPES__NAME = eINSTANCE.getPolyContextTypes_Name();

    /**
     * The meta object literal for the '<em><b>Constraints</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference POLY_CONTEXT_TYPES__CONSTRAINTS = eINSTANCE.getPolyContextTypes_Constraints();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.TypeConstraintsImpl <em>Type Constraints</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.TypeConstraintsImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getTypeConstraints()
     * @generated
     */
    EClass TYPE_CONSTRAINTS = eINSTANCE.getTypeConstraints();

    /**
     * The meta object literal for the '<em><b>Type Name</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE_CONSTRAINTS__TYPE_NAME = eINSTANCE.getTypeConstraints_TypeName();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.TypedVariableImpl <em>Typed Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.TypedVariableImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getTypedVariable()
     * @generated
     */
    EClass TYPED_VARIABLE = eINSTANCE.getTypedVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPED_VARIABLE__NAME = eINSTANCE.getTypedVariable_Name();

    /**
     * The meta object literal for the '<em><b>Constraints</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPED_VARIABLE__CONSTRAINTS = eINSTANCE.getTypedVariable_Constraints();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.TypeDeclarationImpl <em>Type Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.TypeDeclarationImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getTypeDeclaration()
     * @generated
     */
    EClass TYPE_DECLARATION = eINSTANCE.getTypeDeclaration();

    /**
     * The meta object literal for the '<em><b>Type Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE_DECLARATION__TYPE_NAME = eINSTANCE.getTypeDeclaration_TypeName();

    /**
     * The meta object literal for the '<em><b>Context</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE_DECLARATION__CONTEXT = eINSTANCE.getTypeDeclaration_Context();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.TypeDeclContextImpl <em>Type Decl Context</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.TypeDeclContextImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getTypeDeclContext()
     * @generated
     */
    EClass TYPE_DECL_CONTEXT = eINSTANCE.getTypeDeclContext();

    /**
     * The meta object literal for the '<em><b>Type Name</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE_DECL_CONTEXT__TYPE_NAME = eINSTANCE.getTypeDeclContext_TypeName();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.TypeNameImpl <em>Type Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.TypeNameImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getTypeName()
     * @generated
     */
    EClass TYPE_NAME = eINSTANCE.getTypeName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_NAME__NAME = eINSTANCE.getTypeName_Name();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.FunctionNameImpl <em>Function Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.FunctionNameImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getFunctionName()
     * @generated
     */
    EClass FUNCTION_NAME = eINSTANCE.getFunctionName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION_NAME__NAME = eINSTANCE.getFunctionName_Name();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.SupertypeImpl <em>Supertype</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.SupertypeImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getSupertype()
     * @generated
     */
    EClass SUPERTYPE = eINSTANCE.getSupertype();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUPERTYPE__SUPER_TYPE = eINSTANCE.getSupertype_SuperType();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.WhereImpl <em>Where</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.WhereImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getWhere()
     * @generated
     */
    EClass WHERE = eINSTANCE.getWhere();

    /**
     * The meta object literal for the '<em><b>Expessions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHERE__EXPESSIONS = eINSTANCE.getWhere_Expessions();

    /**
     * The meta object literal for the '<em><b>Expressions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHERE__EXPRESSIONS = eINSTANCE.getWhere_Expressions();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.ClassImpl <em>Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.ClassImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getClass_()
     * @generated
     */
    EClass CLASS = eINSTANCE.getClass_();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS__NAME = eINSTANCE.getClass_Name();

    /**
     * The meta object literal for the '<em><b>Context</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS__CONTEXT = eINSTANCE.getClass_Context();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.DatatypeImpl <em>Datatype</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.DatatypeImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getDatatype()
     * @generated
     */
    EClass DATATYPE = eINSTANCE.getDatatype();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATATYPE__NAME = eINSTANCE.getDatatype_Name();

    /**
     * The meta object literal for the '<em><b>Context</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATATYPE__CONTEXT = eINSTANCE.getDatatype_Context();

    /**
     * The meta object literal for the '<em><b>Constructors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATATYPE__CONSTRUCTORS = eINSTANCE.getDatatype_Constructors();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.DatatypeConstructorImpl <em>Datatype Constructor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.DatatypeConstructorImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getDatatypeConstructor()
     * @generated
     */
    EClass DATATYPE_CONSTRUCTOR = eINSTANCE.getDatatypeConstructor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATATYPE_CONSTRUCTOR__NAME = eINSTANCE.getDatatypeConstructor_Name();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.BaseConstructorImpl <em>Base Constructor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.BaseConstructorImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getBaseConstructor()
     * @generated
     */
    EClass BASE_CONSTRUCTOR = eINSTANCE.getBaseConstructor();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.ConstructorImpl <em>Constructor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.ConstructorImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getConstructor()
     * @generated
     */
    EClass CONSTRUCTOR = eINSTANCE.getConstructor();

    /**
     * The meta object literal for the '<em><b>Typed Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTRUCTOR__TYPED_VARIABLES = eINSTANCE.getConstructor_TypedVariables();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.ExtendImpl <em>Extend</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.ExtendImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getExtend()
     * @generated
     */
    EClass EXTEND = eINSTANCE.getExtend();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXTEND__NAME = eINSTANCE.getExtend_Name();

    /**
     * The meta object literal for the '<em><b>Extesnion</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTEND__EXTESNION = eINSTANCE.getExtend_Extesnion();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.TypeBodyElementsImpl <em>Type Body Elements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.TypeBodyElementsImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getTypeBodyElements()
     * @generated
     */
    EClass TYPE_BODY_ELEMENTS = eINSTANCE.getTypeBodyElements();

    /**
     * The meta object literal for the '<em><b>Functions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE_BODY_ELEMENTS__FUNCTIONS = eINSTANCE.getTypeBodyElements_Functions();

    /**
     * The meta object literal for the '<em><b>Theorems</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_BODY_ELEMENTS__THEOREMS = eINSTANCE.getTypeBodyElements_Theorems();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.FunctionDeclImpl <em>Function Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.FunctionDeclImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getFunctionDecl()
     * @generated
     */
    EClass FUNCTION_DECL = eINSTANCE.getFunctionDecl();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_DECL__NAME = eINSTANCE.getFunctionDecl_Name();

    /**
     * The meta object literal for the '<em><b>Type Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_DECL__TYPE_VARIABLES = eINSTANCE.getFunctionDecl_TypeVariables();

    /**
     * The meta object literal for the '{@link org.xtext.sampleProj.mydsl.myDsl.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.ExpressionImpl
     * @see org.xtext.sampleProj.mydsl.myDsl.impl.MyDslPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__NAME = eINSTANCE.getExpression_Name();

  }

} //MyDslPackage
