/**
 * generated by Xtext 2.13.0
 */
package org.xtext.sampleProj.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Instance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sampleProj.mydsl.myDsl.TypeInstance#getInstance <em>Instance</em>}</li>
 *   <li>{@link org.xtext.sampleProj.mydsl.myDsl.TypeInstance#getTypeName <em>Type Name</em>}</li>
 *   <li>{@link org.xtext.sampleProj.mydsl.myDsl.TypeInstance#getElement <em>Element</em>}</li>
 * </ul>
 *
 * @see org.xtext.sampleProj.mydsl.myDsl.MyDslPackage#getTypeInstance()
 * @model
 * @generated
 */
public interface TypeInstance extends EObject
{
  /**
   * Returns the value of the '<em><b>Instance</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Instance</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instance</em>' reference.
   * @see #setInstance(ExpressionVariable)
   * @see org.xtext.sampleProj.mydsl.myDsl.MyDslPackage#getTypeInstance_Instance()
   * @model
   * @generated
   */
  ExpressionVariable getInstance();

  /**
   * Sets the value of the '{@link org.xtext.sampleProj.mydsl.myDsl.TypeInstance#getInstance <em>Instance</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Instance</em>' reference.
   * @see #getInstance()
   * @generated
   */
  void setInstance(ExpressionVariable value);

  /**
   * Returns the value of the '<em><b>Type Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Name</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Name</em>' reference.
   * @see #setTypeName(GenName)
   * @see org.xtext.sampleProj.mydsl.myDsl.MyDslPackage#getTypeInstance_TypeName()
   * @model
   * @generated
   */
  GenName getTypeName();

  /**
   * Sets the value of the '{@link org.xtext.sampleProj.mydsl.myDsl.TypeInstance#getTypeName <em>Type Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Name</em>' reference.
   * @see #getTypeName()
   * @generated
   */
  void setTypeName(GenName value);

  /**
   * Returns the value of the '<em><b>Element</b></em>' reference list.
   * The list contents are of type {@link org.xtext.sampleProj.mydsl.myDsl.TypedVariable}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Element</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' reference list.
   * @see org.xtext.sampleProj.mydsl.myDsl.MyDslPackage#getTypeInstance_Element()
   * @model
   * @generated
   */
  EList<TypedVariable> getElement();

} // TypeInstance
