/**
 * generated by Xtext 2.13.0
 */
package ac.soton.bsharp.ui;

import ac.soton.bsharp.ui.AbstractBSharpUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BSharpUiModule extends AbstractBSharpUiModule {
  public BSharpUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
