/**
 * generated by Xtext 2.13.0
 */
package ac.soton.bsharp;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class BSharpStandaloneSetup /* implements BSharpStandaloneSetupGenerated  */{
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type BSharpStandaloneSetup");
  }
}
