/*
 * generated by Xtext 2.14.0
 */
package ac.soton.bsharp.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBSharpScopeProvider extends DelegatingScopeProvider {
}
