/**
 * generated by Xtext 2.12.0
 */
package org.xtext.sampleProj.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.sampleProj.mydsl.myDsl.FunctionDecl;
import org.xtext.sampleProj.mydsl.myDsl.FunctionName;
import org.xtext.sampleProj.mydsl.myDsl.MyDslPackage;
import org.xtext.sampleProj.mydsl.myDsl.TypedVariable;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Function Decl</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sampleProj.mydsl.myDsl.impl.FunctionDeclImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.sampleProj.mydsl.myDsl.impl.FunctionDeclImpl#getTypeVariables <em>Type Variables</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FunctionDeclImpl extends MinimalEObjectImpl.Container implements FunctionDecl
{
  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected EList<FunctionName> name;

  /**
   * The cached value of the '{@link #getTypeVariables() <em>Type Variables</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeVariables()
   * @generated
   * @ordered
   */
  protected EList<TypedVariable> typeVariables;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FunctionDeclImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.FUNCTION_DECL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<FunctionName> getName()
  {
    if (name == null)
    {
      name = new EObjectContainmentEList<FunctionName>(FunctionName.class, this, MyDslPackage.FUNCTION_DECL__NAME);
    }
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<TypedVariable> getTypeVariables()
  {
    if (typeVariables == null)
    {
      typeVariables = new EObjectContainmentEList<TypedVariable>(TypedVariable.class, this, MyDslPackage.FUNCTION_DECL__TYPE_VARIABLES);
    }
    return typeVariables;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.FUNCTION_DECL__NAME:
        return ((InternalEList<?>)getName()).basicRemove(otherEnd, msgs);
      case MyDslPackage.FUNCTION_DECL__TYPE_VARIABLES:
        return ((InternalEList<?>)getTypeVariables()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.FUNCTION_DECL__NAME:
        return getName();
      case MyDslPackage.FUNCTION_DECL__TYPE_VARIABLES:
        return getTypeVariables();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.FUNCTION_DECL__NAME:
        getName().clear();
        getName().addAll((Collection<? extends FunctionName>)newValue);
        return;
      case MyDslPackage.FUNCTION_DECL__TYPE_VARIABLES:
        getTypeVariables().clear();
        getTypeVariables().addAll((Collection<? extends TypedVariable>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.FUNCTION_DECL__NAME:
        getName().clear();
        return;
      case MyDslPackage.FUNCTION_DECL__TYPE_VARIABLES:
        getTypeVariables().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.FUNCTION_DECL__NAME:
        return name != null && !name.isEmpty();
      case MyDslPackage.FUNCTION_DECL__TYPE_VARIABLES:
        return typeVariables != null && !typeVariables.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //FunctionDeclImpl
